### ISSUE TITLE
Separate URI Template functionality into its own package

### ISSUE THREAD

**Issue by jessealama** [jessealama/argo#4]

**Comment by jackfirth** [comment]
Yes please :)

**Comment by jessealama** [comment]
I'm on it -- stay tuned!

**Comment by jessealama** [comment]
new repo: https://github.com/jessealama/uri-template

**Comment by jessealama** [comment]
work-in-progress package (far from a complete implementation of RFC 6570) submitted to the package server https://pkgd.racket-lang.org/pkgn/package/uri-template . Next step is to make argo depend on this package.
